# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160223_1343'),
        ('projects', '0003_auto_20160112_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
    ]
