# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalgroup',
            name='metric_type',
            field=models.CharField(choices=[(b'Testing', b'Testing'), (b'Development', b'Development'), (b'Requirements', b'Requirements')], default=b'Testing', max_length=13),
        ),
    ]
