# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 20:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_functionalgroup_metric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresource',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
    ]
