# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_humanresource_subteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanresource',
            options={'ordering': ['user__last_name']},
        ),
        migrations.AddField(
            model_name='subteam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
