# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationMetrics',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed', models.DateTimeField(auto_now=True, db_index=True)),
                ('staffs', models.IntegerField(default=0)),
                ('contractors', models.IntegerField(default=0)),
                ('openings', models.IntegerField(default=0)),
                ('slas_met', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('delays_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('sdis_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('escalations', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('avg_team_size', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekday', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekend', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('license_cost', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('other_savings', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('story_points_backlog', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('story_points_prep', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('story_points_execution', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('unit_tests_dev', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('unit_tests_coverage', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('documentation_coverage', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('defects_in_dev', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('elicitation_analysis_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('revisions', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('active_projects', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('uat_defects_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('pheme_manual_tests', models.DecimalField(default=0, max_digits=19, decimal_places=2)),
                ('pheme_auto_tests', models.DecimalField(default=0, max_digits=19, decimal_places=2)),
                ('visilog_txl_parsed', models.DecimalField(default=0, max_digits=19, decimal_places=2)),
                ('visilog_txl_schema_violation', models.DecimalField(default=0, max_digits=19, decimal_places=2)),
                ('functional_group', models.ForeignKey(to='users.FunctionalGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabMetrics',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed', models.DateTimeField(auto_now=True, db_index=True)),
                ('staffs', models.IntegerField(default=0)),
                ('contractors', models.IntegerField(default=0)),
                ('openings', models.IntegerField(default=0)),
                ('slas_met', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('delays_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('sdis_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('escalations', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('avg_team_size', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekday', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekend', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('license_cost', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('other_savings', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tickets_received', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tickets_closed', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('virtual_machines', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('physical_machines', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('power_consumption_ups_a', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('power_consumption_ups_b', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('functional_group', models.ForeignKey(to='users.FunctionalGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementMetrics',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed', models.DateTimeField(auto_now=True, db_index=True)),
                ('staffs', models.IntegerField(default=0)),
                ('contractors', models.IntegerField(default=0)),
                ('openings', models.IntegerField(default=0)),
                ('slas_met', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('delays_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('sdis_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('escalations', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('avg_team_size', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekday', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekend', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('license_cost', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('other_savings', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('backlog', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('team_initiative', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('active_projects', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('elicitation_analysis_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('revisions', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('slas_missed', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('rework_external_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('travel_cost', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('functional_group', models.ForeignKey(to='users.FunctionalGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMetrics',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed', models.DateTimeField(auto_now=True, db_index=True)),
                ('staffs', models.IntegerField(default=0)),
                ('contractors', models.IntegerField(default=0)),
                ('openings', models.IntegerField(default=0)),
                ('slas_met', models.DecimalField(default=0, max_digits=3, decimal_places=2, validators=[django.core.validators.MaxValueValidator(1)])),
                ('delays_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('sdis_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('escalations', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_introduced_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('avg_team_size', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekday', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('overtime_weekend', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('rework_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('resource_swap_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('license_cost', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('other_savings', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('team_initiative', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('ticket_backlog', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('ticket_prep', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('ticket_execution', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('ticket_closed', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('project_backlog', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('project_prep', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('project_execution', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('project_closed', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_manual_dev', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_manual_dev_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_manual_execution', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_manual_execution_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_auto_dev', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_auto_dev_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_auto_execution', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('tc_auto_execution_time', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('defect_caught', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('uat_defects_not_prevented', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('avg_time_frame', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('functional_group', models.ForeignKey(to='users.FunctionalGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
