# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160223_1343'),
        ('teams', '0009_auto_20160225_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationmetrics',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
        migrations.AddField(
            model_name='labmetrics',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
        migrations.AddField(
            model_name='requirementmetrics',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
        migrations.AddField(
            model_name='testmetrics',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subteam'),
        ),
        migrations.AlterField(
            model_name='innovationmetrics',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionalGroup'),
        ),
        migrations.AlterField(
            model_name='labmetrics',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionalGroup'),
        ),
        migrations.AlterField(
            model_name='requirementmetrics',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionalGroup'),
        ),
        migrations.AlterField(
            model_name='testmetrics',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionalGroup'),
        ),
    ]
