# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20160301_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationmetrics',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='labmetrics',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='requirementmetrics',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='testmetrics',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
    ]
