# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0004_teststats_resource_swap_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innovationstats',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='labstats',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='requirementstats',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='teststats',
            options={'ordering': ['-created']},
        ),
    ]
